spring:
  application:
    name: service-price
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
server:
  servlet:
    context-path: /inditex